<div class="bookmarklet">
<a href="javascript:var%20b=document.body;var%20GR________bookmarklet_domain='http://www.google.com';if(b&&!document.xmlVersion){void(z=document.createElement('script'));void(z.src='http://www.google.com/reader/ui/link-bookmarklet.js');void(b.appendChild(z));}else{}" title="Share on Google Reader"><img src="https://www.google.com/reader/ui/favicon.ico" alt="Google Reader" /></a>
<a href="javascript:location.href='http://myweb2.search.yahoo.com/myresults/bookmarklet?u='+encodeURIComponent(location.href)+'&amp;t='+encodeURIComponent(document.title)" title="Bookmark on Yahoo"><img src="https://www.google.com/s2/favicons?domain_url=http://www.yahoo.com/" alt="Yahoo" /></a>
<a href="javascript:var%20d=document,f='http://www.facebook.com/share',l=d.location,e=encodeURIComponent,p='.php?src=bm&amp;v=4&amp;i=1247582208&amp;u='+e(l.href)+'&amp;t='+e(d.title);1;try{if%20(!/^(.*\.)?facebook\.[^.]*$/.test(l.host))throw(0);share_internal_bookmarklet(p)}catch(z)%20{a=function()%20{if%20(!window.open(f+'r'+p,'sharer','toolbar=0,status=0,resizable=1,width=626,height=436'))l.href=f+p};if%20(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}}void(0)" title="Share on Facebook"><img src="https://www.google.com/s2/favicons?domain_url=http://www.facebook.com/" alt="Facebook" /></a>
<a href="javascript:void(location.href='http://twitter.com/home?status=Now%20reading%20&lt;&lt;'+encodeURIComponent(document.title)+'&gt;&gt;%20'+encodeURIComponent(location.href))" title="Twitter This"><img src="https://www.google.com/s2/favicons?domain_url=http://twitter.com/" alt="Twitter" /></a>
<a href="javascript:window.open('http://digg.com/submit?phase=2&amp;url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title))()" title="Digg it"><img src="https://www.google.com/s2/favicons?domain_url=http://digg.com/" alt="Digg" /></a>
<a href="javascript:void((function(){var%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('src','http://friendfeed.com/share/bookmarklet/javascript');document.body.appendChild(e)})())" title="Share on FriendFeed"><img src="https://www.google.com/s2/favicons?domain_url=http://friendfeed.com/" alt="FriendFeed" /></a>
<a href="javascript:location.href='http://del.icio.us/post?v=4;url='+encodeURIComponent(location.href)+';title='+encodeURIComponent(document.title)" title="Share on Delicious"><img src="http://www.google.com/s2/favicons?domain_url=http://delicious.com/" alt="Delicious" /></a>
<a href="javascript:location='http://translate.google.com/translate?u='%20+%20encodeURIComponent(location);" title="Translate this page"><img src="http://www.google.com/s2/favicons?domain_url=https://translate.google.com/" alt="Google Translate" /></a>
</div>
